# Generated by Django 5.1.4 on 2025-02-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_views_counter_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
