# Generated by Django 4.2.5 on 2025-02-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_unpublication_product', 'can unpublication product'), ('can_delete_product', 'can delete product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterModelTable(
            name='product',
            table=('custom_table_name',),
        ),
    ]
